### ISSUE TITLE
无法编译

### ISSUE THREAD

**Issue by liuziangexit** [0xJacky/randomCall#1]
为什么会变成这样呢
![image](https://user-images.githubusercontent.com/15322450/36187928-8d9d770c-1183-11e8-9715-b79410e5e56c.png)

**Comment by 0xJacky** [comment]
呃 你先在 Windows 上安装个 python

然后 pip install pyinstaller

**Comment by liuziangexit** [comment]
额，真的可以了诶！

但是编译出来的可执行文件在哪里呢

**Comment by 0xJacky** [comment]
`dist/randomCall` 里

**Comment by liuziangexit** [comment]
![image](https://user-images.githubusercontent.com/15322450/36188451-0ef7e32a-1187-11e8-9d17-70c4dca0029b.png)
有编译错误。。。不懂Python，就不麻烦大佬了。。。

**Comment by 0xJacky** [comment]
我等会检查下
话说你是 python3 吧？

发自我的 iPhone

**Comment by liuziangexit** [comment]
是的，是Python3

**Comment by 0xJacky** [comment]
emmm 我是在 Python 2.7 下编写的

Python 3 下是不能成功编译的，我等会打包一个 release 吧

**Comment by liuziangexit** [comment]
老板牛逼！
